version: '3.8'

services:
  # MySQL Baza podataka
  db:
    image: mysql:8.0
    container_name: twitter_db
    restart: always
    environment:
      MYSQL_DATABASE: twitter_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Backend API
  backend:
    build: ./backend
    container_name: twitter_api
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=twitter_db
    depends_on:
      - db

  # WebSocket Server
  websocket:
    build: ./websocket
    container_name: twitter_ws
    ports:
      - "4000:4000"
    depends_on:
      - backend

  # Frontend React
  frontend:
    build: ./frontend
    container_name: twitter_ui
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  db_data: