version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: twitter_db
    restart: always
    environment:
      MYSQL_DATABASE: twitter_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: twitter_api
    restart: on-failure # Ako se baza ne digne odmah, backend Ä‡e se restartati
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword # Promijenjeno da odgovara configu
      - DB_NAME=twitter_db
      - PORT=3000
    depends_on:
      - db

  websocket:
    build: ./websocket
    container_name: twitter_ws
    volumes:
      - ./websocket:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - BACKEND_URL=http://backend:3000 # Za komunikaciju unutar dockera
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: twitter_ui
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
  
volumes:
  db_data: